name: Build Engine

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        default: '4.3-stable'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux]
    steps:
    - uses: actions/checkout@v3
    - name: Clone git repo using build.sh to correct version
      run: |
        ./build.sh -v ${{ inputs.tag }} -g ${{ inputs.tag }} -b classical

    - name: Build
      run: |
        ./build.sh -v ${{ inputs.tag }} -g ${{ inputs.tag }} -b classical -c -p ${{ matrix.platform }}
